#####----- PATHS AND SYSTEM SETTINGS FOR ALL ANALYSIS SCRIPTS

## Each section below defines the parameters for a specific analysis code. Any parameters that need to be added, deleted, or modified should be done so here

#####----- compare_weights.py CONFIG
compare_weights:
  weights_path_1: ""
  path_1_type: ""
  weights_path_2: ""
  path_2_type: ""
  save_path: ""
  cutoff: ""

#####----- curve_compare.py CONFIG
curve_compare:
  experimental_data: "/users/t/j/tjaglal/experimental_data/SASDLU4.dat"
  structure_path: "/users/t/j/tjaglal/structures"
  output_path: "/gpfs1/home/t/j/tjaglal/Projects/iBME/iBME_res/iBME_dro_-26.72_to_70.14_r0r_.850_to_1.10_t2000"
  lent: 5000
  post_weights_1: "/gpfs1/home/t/j/tjaglal/Projects/iBME/iBME_res/iBME_dro_-26.72_to_70.14_r0r_.850_to_1.10_t2000/structure_weights_sorted_2026-05-20.txt" 
  grid_sum_1: "/gpfs1/home/t/j/tjaglal/Projects/iBME/iBME_res/iBME_dro_-26.72_to_70.14_r0r_.850_to_1.10_t2000/GRID_sum.txt"
  save_path_1: "/users/t/j/tjaglal/Projects/iBME/grid_sims/saxs_dro_-26.72_to_70.14_r0_1.36_to_1.76"
  best_dro_1: 30.06
  best_r0_1: 0.850
  post_weights_2: "/gpfs1/home/t/j/tjaglal/Projects/iBME/iBME_res/iBME_dro_-26.72_to_70.14_r0r_.850_to_1.10_t2000/structure_weights_sorted_2026-05-20.txt" 
  grid_sum_2: "/gpfs1/home/t/j/tjaglal/Projects/iBME/iBME_res/iBME_dro_-26.72_to_70.14_r0r_.850_to_1.10_t2000/GRID_sum.txt"
  save_path_2: "/users/t/j/tjaglal/Projects/iBME/grid_sims/saxs_dro_-26.72_to_70.14_r0_1.36_to_1.76"
  best_dro_2: -16.7
  best_r0_2: 0.850


#####----- ensemble_fit.py CONFIG
ensemble_fit:
  path_exp_file: "/gpfs1/home/t/j/tjaglal/experimental_data/SASDLS4.dat"
  structure_path: "/gpfs1/home/t/j/tjaglal/cterm_structures"
  dro: 0.00
  r0: 1.05
  save_path: "/users/t/j/tjaglal/Projects/iBME/cterm_grid_sims/saxs_dro_-26.72_to_70.14_r0_1.36_to_1.76"
  sim_path: "/gpfs1/home/t/j/tjaglal/Projects/iBME/cterm_iBME_res/iBME_dro_-26.72_to_70.14_r0_1.36_to_1.76_t100"

#####----- file_curve.py CONFIG
file_curve:
  path_exp_file: "/users/t/j/tjaglal/experimental_data"
  search_path: "/users/t/j/tjaglal"
  save_path: "/users/t/j/tjaglal/Projects/iBME/analysis"

#####----- plot_theta.py CONFIG
plot_theta:
  out_path: "/users/t/j/tjaglal/Projects/iBME/theta_scan/"
  dro_min: -26.72
  dro_max: 13.36
  r0_min: 1.36
  r0_max: 1.68
  theta_val_1: 10
  theta_val_2: 100
  theta_val_3: 500
  theta_val_4: 1000
  theta_val_5: 2000
  theta_val_6: 4000
  theta_val_7: 6000

#####----- Rg_compare.py CONFIG
rg_compare:
  experimental_data: "/users/t/j/tjaglal/experimental_data"
  experimental_rg: 67
  post_weights_path: ""
  save_path: ""
  grid_path: "/GRID_sun.txt"
  out_path: ""
  best_dro: 30
  best_r0: 1.343

#####----- Rg_gps.py CONFIG
rg_gps:
  experimental_data: "/users/t/j/tjaglal/experimental_data/SASDLU4.dat"
  experimental_rg: 67
  output_path: "/users/t/j/tjaglal/Projects/iBME"
  post_weights_1: "/users/t/j/tjaglal/Projects/iBME/iBME_res/iBME_dro_-26.72_to_70.14_r0r_.850_to_1.10_t100/structure_weights_sorted_2026-06-09.txt"
  grid_sum_1: "/users/t/j/tjaglal/Projects/iBME/iBME_res/iBME_dro_-26.72_to_70.14_r0r_.850_to_1.10_t100/GRID_sum.txt"
  save_path_1: "/users/t/j/tjaglal/Projects/iBME/grid_sims/saxs_dro_-26.72_to_70.14_r0_1.36_to_1.76"
  best_dro_1: -23.38
  best_r0_1: .850
  post_weights_2: "/users/t/j/tjaglal/Projects/iBME/iBME_res/iBME_dro_-26.72_to_70.14_r0r_.850_to_1.10_t100/structure_weights_sorted_2026-06-09.txt"
  grid_sum_2: "/users/t/j/tjaglal/Projects/iBME/iBME_res/iBME_dro_-26.72_to_70.14_r0r_.850_to_1.10_t100/GRID_sum.txt"
  save_path_2: "/users/t/j/tjaglal/Projects/iBME/grid_sims/saxs_dro_-26.72_to_70.14_r0_1.36_to_1.76"
  best_dro_2: -13.36
  best_r0_2: .850

#####----- file_curve.py CONFIG
file_curve:
  path_exp_file: "/users/t/j/tjaglal/experimental_data/SASDLU4.dat"
  search_path: "/users/t/j/tjaglal/structures/pepsi_out"
  save_path: "/users/t/j/tjaglal/structures/pepsi_out"
  file_1: "mm032_796"
  file_2: "mm016_661"
  file_3: "mm032_681"
  file_4: "mm016_874"
  file_5: "mm032_586"
  file_6: "mm032_646"
  file_7: "mm032_766"
  file_8: "mm064_465"
  file_9: "mm064_405"
  file_10: "mm016_673"

#####----- cumulative_weights.py CONFIG
cumulative_weights:
  reweighted_path:
  save_path: 

#####----- pepsi_fit.py CONFIG
pepsi_fit:
  structure_path: "/users/t/j/tjaglal/structures" 
  path_exp_file: "/users/t/j/tjaglal/experimental_data/SASDLU4.dat"
  path_to_pepsi: "/users/t/j/tjaglal/Projects/iBME"
  summary_file: "/users/t/j/tjaglal/Projects/iBME/pepsi_fit_summary.txt"
  cutoff: 10
  output_dir_path: "/users/t/j/tjaglal/structures/pepsi_out"

#####----- save_weights.py CONFIG
save_weights:
  save_path: "/gpfs1/home/t/j/tjaglal/Projects/iBME/cterm_grid_sims/saxs_dro_-26.72_to_70.14_r0_1.36_to_1.76"
  struc_path: "/users/t/j/tjaglal/cterm_structures"
  ibme_out_dir: "/gpfs1/home/t/j/tjaglal/Projects/iBME/cterm_iBME_res/iBME_dro_-26.72_to_70.14_r0_1.36_to_1.76_t100"
  type: "opt"
  custom_dro: ""
  custom_r0: ""

#####----- pepsi_iteration.py CONFIG
pepsi_iteration:
  sim_path: "/users/t/j/tjaglal/Projects/iBME/grid_sims/saxs_dro_-26.72_to_70.14_r0_1.36_to_1.76"
  summary_file: "/users/t/j/tjaglal/Projects/iBME/grid_sims/saxs_dro_-26.72_to_70.14_r0_1.36_to_1.76/pepsi_fit.txt"
  gps: 340
  type: "full" #"c_term" or "full"
  cutoff: 10
